name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      env:
        GIT_HASH: $(git rev-parse --short "$GITHUB_SHA")
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build -t docker.pkg.github.com/gonglowbat/basic-nginx-docker/basic-docker-nginx:$GIT_HASH .
        env: git_hash=$(git rev-parse --short "$GITHUB_SHA")

      - name: Push Docker image to Github Packages
        run: docker push docker.pkg.github.com/gonglowbat/basic-nginx-docker/basic-docker-nginx:$GIT_HASH
